language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"

os:
    - linux
    - osx

before_install:
    - pip install numpy

install:
    - pip install .

script:
    - nosetests --with-doctest

notifications:
    email: false
