language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"

os:
    - linux
    - osx

before_install:
    - pip install nose numpy scipy

install:
    - python setup.py install

script:
    - nosetests --with-doctest

notifications:
    email: false
